### ISSUE TITLE
route and nc not found

### ISSUE THREAD

**Issue by dublx** [mhamrah/docker-envconsul#1]
Hi,
When running the container the following errors occur:
```sh
/usr/bin/envconsul-launch: 3: /usr/bin/envconsul-launch: route: not found
/usr/bin/envconsul-launch: 6: /usr/bin/envconsul-launch: nc: not found
WARNING! Consul not available, running locally.
```
Any ideas?

**Comment by mhamrah** [comment]
Hey, sorry about that! I don't think I installed nc and route properly. I
copied this from another container I was working on in a private repo, and
haven't updated the github template. I'll do that shortly, and I also have
a much better start script.

If you can't wait, just use this as a base container, install net-tools,
and you should be good to go.
